### ISSUE TITLE
RX

### ISSUE THREAD

**Issue by sisar1337** [InsaneSlay/osu-Presence#1]
If you use the relax mod, no mod will show up - not even relax

**Comment by InsaneSlay** [comment]
hi, support for other mods such as Relax, Auto Pilot, etc will be added later on today.

**Comment by sisar1337** [comment]
nice :D

**Comment by InsaneSlay** [comment]
fixed in [latest release (v0.2-a)](https://github.com/InsaneSlay/osuPresence/releases/tag/v0.2-a) w/ source :  https://github.com/InsaneSlay/osuPresence/commit/faa41ad497a820c58dba97d888ad0e0676a7570f
